### ISSUE TITLE
Tags "unavailable" after HA restart inside HA (Server management - Restart). Requires total HA server restart (shut down virtual server and restart).

### ISSUE THREAD

**Issue by qzstr** [oiv/ruuvigw_node-red_ha#3]
Thank you for the integration and your work with it!

Issue as in the topic. Waiting for any amount of time may make one or few tags visible, but sporadically. All tags visible again after full restart. 

Using latest version of HA. Once the data is flowing have not seen issues.

**Comment by oiv** [comment]
Hmm. Need to check. The script should send the config message every 10 minutes. So after around 10 minutes everything should be ok.
Anyways. I will deploy a change where the config message is sent more often. I guess there is no harm. Esp-home seems to send it really often.

**Comment by oiv** [comment]
The new version makes now the wait for tags to show active hopefully shorter.
The configuration message to home-assistant is not retained and anyway sent every minute. Not sure it is wise but this helps.
